class Transaction {
  Transaction({
    required this.id,
    required this.ledgerId,
    required this.amount,
    required this.type,
    required this.category,
    required this.method,
    required this.date,
    required this.notes,
    this.isAutoGenerated = false,
  });

  final String id;
  final String ledgerId;
  final double amount;
  final String type;
  final String category;
  final String method;
  final String date;
  final String notes;
  final bool isAutoGenerated;

  Transaction copyWith({
    String? id,
    String? ledgerId,
    double? amount,
    String? type,
    String? category,
    String? method,
    String? date,
    String? notes,
    bool? isAutoGenerated,
  }) {
    return Transaction(
      id: id ?? this.id,
      ledgerId: ledgerId ?? this.ledgerId,
      amount: amount ?? this.amount,
      type: type ?? this.type,
      category: category ?? this.category,
      method: method ?? this.method,
      date: date ?? this.date,
      notes: notes ?? this.notes,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'ledgerId': ledgerId,
        'amount': amount,
        'type': type,
        'category': category,
        'method': method,
        'date': date,
        'notes': notes,
        'isAutoGenerated': isAutoGenerated,
      };

  factory Transaction.fromJson(Map<String, dynamic> json) {
    return Transaction(
      id: json['id'] as String,
      ledgerId: json['ledgerId'] as String,
      amount: (json['amount'] as num).toDouble(),
      type: json['type'] as String,
      category: json['category'] as String,
      method: json['method'] as String,
      date: json['date'] as String,
      notes: json['notes'] as String? ?? '',
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
    );
  }
}
